data_root: /data/jionkim/_TTE_images_res_192/
work_dir: /data/jionkim/Slim_UNETR/

finetune:
  checkpoint: brain2021_4
  slim_unetr:
    in_channels: 1
    out_channels: 2
    embed_dim: 96 
    embedding_dim: 64 #216 
    channels: [ 24, 48, 60 ]
    blocks: [ 1, 2, 3, 2 ]
    heads: [ 1, 2, 4, 4 ]
    r: [ 4, 2, 2, 1 ]
    dropout: 0.3

trainer:
  num_epochs: 3000
  warmup: 5
  train_ratio: 0.8
  batch_size: 1
  lr: 0.002
  min_lr: 0.0000002
  optimizer: adamw
  weight_decay: 0.05
  weight_decay_end: 0.04
  momentum_teacher: 0.996
  pred_ratio_var: 0
  num_workers: 16
  image_size: 192
  save_cycle: 100 #저장 간격
  resume: False

inference:
  epoch: best
  pathseg: train
  #finetune.checkpoint 과 같은 이름의 train folder load

generation:
  epoch: best
  pathseg: train
  #finetune.checkpoint 과 같은 이름의 train folder load

# 폴더 구조
#
#    /Slim_UNETR(work_dir)
#        ㅣ
#        ㅏ train
#        ㅣ   ㅏ logs
#        ㅣ   ㅏ model_store
#        ㅣ
#        ㅏ inference
#        ㅣ   ㅏ logs
#        ㅣ   ㅏ model_store
#        ㅣ
#        ㅏ generation
#        ㅣ   ㅏ logs
#        ㅣ   ㅏ model_store